springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true

application.transactions-db.url=jdbc:h2:file:./transaction
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

application.rules.part01.url=jdbc:h2:file:./recommendationsPart01
application.rules.part01.username=sa
application.rules.part01.password=
application.rules.part01.driver-class-name=org.h2.Driver

application.rules.part02.url=jdbc:h2:file:./recommendationsPart02
application.rules.part02.username=sa
application.rules.part02.password=
application.rules.part02.driver-class-name=org.h2.Driver

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema-init.sql